name: build

on: [ push, pull_request ]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" , "3.12"]
        postgres-version: [ "16"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 'python-config'
        run: |
          echo 'cflags'
          python${{ matrix.python-version }}-config --cflags
          
          echo 'includes'
          python${{ matrix.python-version }}-config --includes
          
          echo 'ldflags'
          python${{ matrix.python-version }}-config --ldflags
          
          echo 'embed'
          python${{ matrix.python-version }}-config --embed
          
          echo 'libs'
          python${{ matrix.python-version }}-config --libs

      - name: 'Install PostgreSQL'
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg-snapshot main ${{ matrix.postgres-version }}" > /etc/apt/sources.list.d/pgdg.list'
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null
          sudo apt-get update
          sudo apt-get -y install postgresql-${{ matrix.postgres-version }} postgresql-server-dev-${{ matrix.postgres-version }}  

      - name: 'Start PostgreSQL'
        run: |
          export PGDATA=/var/lib/postgresql/${{ matrix.postgres-version }}/main
          export PGETC=/etc/postgresql/${{ matrix.postgres-version }}/main
          export PGBIN=/usr/lib/postgresql/${{ matrix.postgres-version }}/bin
          sudo cp ./ci/pg_hba.conf $PGETC/pg_hba.conf
          sudo su postgres -c "$PGBIN/pg_ctl --pgdata $PGDATA start -o '-c config_file=$PGETC/postgresql.conf -p 5432'" || exit 1

      - name: 'make all'
        run: |
          CC=/usr/bin/gcc PYTHON=$pythonLocation/python${{ matrix.python-version }} PG_CFLAGS=$(python${{ matrix.python-version }}-config --includes) PG_LDFLAGS=$(python${{ matrix.python-version }}-config --ldflags) make clean test-python-embedding pgpyembed.o

      - name: 'Stop PostgreSQL'
        run: |
          export PGBIN=/usr/lib/postgresql/${{ matrix.postgres-version }}/bin
          sudo su postgres -c "$PGBIN/pg_ctl stop -D /var/lib/postgresql/${{ matrix.postgres-version }}/main"
