name: build

on: [ push, pull_request ]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" , "3.12"]
        postgres-version: [ "16"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 'python-config'
        run: |
          echo 'cflags'
          python${{ matrix.python-version }}-config --cflags
          
          echo 'includes'
          python${{ matrix.python-version }}-config --includes
          
          echo 'ldflags'
          python${{ matrix.python-version }}-config --ldflags
          
          echo 'embed'
          python${{ matrix.python-version }}-config --embed
          
          echo 'libs'
          python${{ matrix.python-version }}-config --libs

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          build-essential \
          libreadline-dev \
          zlib1g-dev \
          flex \
          bison \
          libxml2-dev \
          libxslt1-dev \
          libssl-dev \
          libcurl4-openssl-dev \
          libkrb5-dev \
          libpam0g-dev \
          libldap2-dev \
          libedit-dev \
          wget

      - name: Download PostgreSQL
        run: |
          wget https://ftp.postgresql.org/pub/source/v16.1/postgresql-16.1.tar.gz
          tar -xzf postgresql-16.1.tar.gz
          cd postgresql-16.1

      - name: Build PostgreSQL
        run: |
          cd postgresql-16.1
          CC=/usr/bin/gcc ./configure --prefix=/usr/lib/postgresql/${{ matrix.postgres-version }}
          make
          sudo make install

      - name: 'Start PostgreSQL'
        run: |
          export PGDATA=/var/lib/postgresql/${{ matrix.postgres-version }}/main
          export PGETC=/etc/postgresql/${{ matrix.postgres-version }}/main
          export PGBIN=/usr/lib/postgresql/${{ matrix.postgres-version }}/bin
          sudo cp ./ci/pg_hba.conf $PGETC/pg_hba.conf
          sudo su postgres -c "$PGBIN/pg_ctl --pgdata $PGDATA start -o '-c config_file=$PGETC/postgresql.conf -p 5432'" || exit 1

      - name: 'make all'
        run: |
          CC=/usr/bin/gcc PYVERSION=${{ matrix.python-version }} PYTHON=$pythonLocation/python${{ matrix.python-version }} PG_CFLAGS=$(python${{ matrix.python-version }}-config --includes) PG_LDFLAGS=$(python${{ matrix.python-version }}-config --ldflags) make clean test-python-embedding all

      - name: 'Stop PostgreSQL'
        run: |
          export PGBIN=/usr/lib/postgresql/${{ matrix.postgres-version }}/bin
          sudo su postgres -c "$PGBIN/pg_ctl stop -D /var/lib/postgresql/${{ matrix.postgres-version }}/main"
