name: build

on: [ push, pull_request ]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 'python-config'
        run: |
          echo 'cflags'
          python${{ matrix.python-version }}-config --cflags --ldflags --embed 
          echo 'ldflags'
          python${{ matrix.python-version }}-config --ldflags
          echo 'embed'
          python${{ matrix.python-version }}-config --embed
          echo 'libs'
          python${{ matrix.python-version }}-config --libs


      - name: 'cc call.c'
        run: |
          gcc -o call call.c $(python${{ matrix.python-version }}-config --cflags --ldflags)

